### PR TITLE
Editor: move client side code apart

### LINKED ISSUE #3875: Browser's native Cmd/Ctrl+<N> is blocked everywhere
**Describe the bug**
In any Weblate page, pressing Cmd/Ctrl+\<N\> (N being a tab number), will prevent browser's default behavior, which is to change switch to a specific tab.

**To Reproduce**
1. Go to any Weblate page
2. Press Cmd/Ctrl+\<N\> (where N != current tab number)

**Expected behavior**
I understand this is desired behavior for translate pages to enhance the translating experience, however it shouldn't be the case for any other page. Altering/hijacking browser native functionality is usually bad practice, and it interrupts visitors and their expectations.

### PR DESCRIPTION
**Pull request by julen**
This moves the code as-is from a globally-included script file to an
editor-specific script. It includes code for both regular and zen mode
editing.

Further improvements should be made on top of this to avoid leaking
global variables and/or ensuring only editor mode-specific code is
initialized.

Fixes #3875.

### CODE REVIEW

**Comment by julen** [comment]
@nijel I'm not 100% familiar with all Weblate features so please do check if something has been inadvertently broken. I did my best to identify editor-specific code, but if you spot any leftovers in _loader-bootstrap.js_, please let me know.

File: weblate/static/loader-bootstrap.js [hunk 1]
```diff
@@ -850,71 +435,6 @@ $(function () {
         }
     }
 
-    /* Translation editor */
-    Mousetrap.bindGlobal(
-        ['alt+enter', 'mod+enter'],
-        submitForm
-    );
```
Comment (nijel) [inline weblate/static/loader-bootstrap.js:857]: This is used to submit form anywhere, it's not specific to the editor.

File: weblate/static/loader-bootstrap.js [hunk 2]
```diff
@@ -1449,21 +704,6 @@ $(function () {
     /* Copy to clipboard */
     var clipboard = new ClipboardJS('[data-clipboard-text]');
 
-    /* Auto translate source select */
```
Comment (nijel) [inline weblate/static/loader-bootstrap.js:1452]: This block is not for the editor page, auto translate is standalone.

File: weblate/static/loader-bootstrap.js [hunk 3]
```diff
@@ -980,69 +464,6 @@ $(function () {
         $window.scrollTop($(href).offset().top);
     });
```
Comment (nijel) [inline weblate/static/loader-bootstrap.js:465]: This is IMHO for editor as well.

File: weblate/static/loader-bootstrap.js (hunk 1 above)
Comment (julen) [reply weblate/static/loader-bootstrap.js:857]: Do you have any pointers where? I understand this is needed in the editor because it's a textarea, but any other regular forms can/should be natively submitted by pressing <kbd>Enter</kbd> (the `submit` event can be captured to attach XHR behavior).

Comment (nijel) [reply weblate/static/loader-bootstrap.js:857]: For example, settings or addon configuration forms have textareas and it's useful there as well to submit with Ctrl+Enter.

**Comment by julen** [comment]
Ok, all comments have been addressed — please let me know if anything else is missing.

**Comment by nijel** [comment]
Merged, thanks for your contribution!
